language: python

matrix:
  include:
    - python: "3.4"
install: 
  - sudo apt-get install libqt4-dev
  - pip install --find-links https://parkin.github.io/test-travis-python-3.4-system-site/ --use-wheel PySide;

script:
  - python test.py

notifications:
  email: false

